String selectCategory = 'Select a category';
String lorem =
    'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.';
String readFullArticle = 'read full article to earn points';
String readMore = 'Read more';
String readMoreBulletins = 'Read more Bulletins';
String points = 'Points';
String hidoc = 'Hidoc';
String hidocButtin = 'Hidoc Bulletin';
String latestArticles = 'Latest Articles';
String exploreMoreInArticles = 'Explore more in Articles';
String exploreHidocDr = 'Explore Hidoc Dr';
String news = 'News';
String medicalCalculator = 'Medical Calculator : ';
String quizzes = 'Quizzes : ';
String visit = 'Visit';
String reachUs = 'Reach Us';
String email = 'Email';
String address = 'Address';
